[package]
name = "git-merkle-ing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
git2 = "0.16.1"
tempdir = "0.3.7"
