version: "3"
services:
  pricedump:
    volumes:
      - static-content:/root/static
    restart: always
    build:
      context: ..
      dockerfile: etl_pricedumping/Dockerfile
    command: python3 -u price-timestamping/etl_pricedumping/pricedumping.py
    networks:
      - app_gateway
  hash_api:
    volumes:
      - static-content:/root/static
    restart: always
    build:
      context: ..
      dockerfile: etl_pricedumping/Dockerfile
    command: python3 -u price-timestamping/etl_pricedumping/wsgi.py
    ports:
      - "6501:6501"
  watcher:
    volumes:
      - static-content:/root/static
    restart: always
    build:
      context: ..
      dockerfile: etl_pricedumping/Dockerfile
    command: python3 -u price-timestamping/credit_tracking/tx-watcher.py

networks:
  app_gateway: #same network that priceapi is using
    external: true
volumes:
  static-content:
